"""add avatar and theme to profiles

Revision ID: 41947c47e819
Revises: 6be2b65152bc
Create Date: 2026-08-05 01:39:17.041212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41947c47e819'
down_revision: Union[str, None] = '6be2b65152bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_data_url', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('theme', sa.String(length=10), server_default='system', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'theme')
    op.drop_column('profiles', 'avatar_data_url')
    # ### end Alembic commands ###
