"""expand catalog listing attributes

Revision ID: 6be2b65152bc
Revises: 984554351b61
Create Date: 2026-07-27 17:19:53.875654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be2b65152bc'
down_revision: Union[str, None] = '984554351b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_listings', sa.Column('short_description', sa.String(length=500), nullable=True))
    op.add_column('catalog_listings', sa.Column('sales_unit', sa.Enum('strand', 'container', 'bag', 'tube', 'count', 'gram', 'ounce', 'piece', 'pair', 'set', 'unknown', 'other', 'lot', name='unittype', native_enum=False, length=20), nullable=True))
    op.add_column('catalog_listings', sa.Column('quantity_per_listing', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('catalog_listings', sa.Column('available_quantity_mode', sa.Enum('manual', 'derived_from_inventory', 'not_tracked', name='availablequantitymode', native_enum=False, length=30), nullable=False, server_default='not_tracked'))
    op.add_column('catalog_listings', sa.Column('manual_available_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('catalog_listings', sa.Column('category_override_id', sa.Uuid(), nullable=True))
    op.add_column('catalog_listings', sa.Column('subtype_override', sa.String(length=100), nullable=True))
    op.add_column('catalog_listings', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('catalog_listings', sa.Column('collection_theme', sa.String(length=150), nullable=True))
    op.add_column('catalog_listings', sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_listings', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('catalog_listings', sa.Column('seo_title', sa.String(length=255), nullable=True))
    op.add_column('catalog_listings', sa.Column('seo_description', sa.String(length=500), nullable=True))
    op.add_column('catalog_listings', sa.Column('listing_notes', sa.String(), nullable=True))
    op.add_column('catalog_listings', sa.Column('publish_readiness', sa.Enum('missing_photos', 'needs_pricing', 'needs_description', 'ready', name='publishreadiness', native_enum=False, length=30), nullable=True))
    op.create_foreign_key(None, 'catalog_listings', 'product_categories', ['category_override_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog_listings', type_='foreignkey')
    op.drop_column('catalog_listings', 'publish_readiness')
    op.drop_column('catalog_listings', 'listing_notes')
    op.drop_column('catalog_listings', 'seo_description')
    op.drop_column('catalog_listings', 'seo_title')
    op.drop_column('catalog_listings', 'sort_order')
    op.drop_column('catalog_listings', 'featured')
    op.drop_column('catalog_listings', 'collection_theme')
    op.drop_column('catalog_listings', 'tags')
    op.drop_column('catalog_listings', 'subtype_override')
    op.drop_column('catalog_listings', 'category_override_id')
    op.drop_column('catalog_listings', 'manual_available_quantity')
    op.drop_column('catalog_listings', 'available_quantity_mode')
    op.drop_column('catalog_listings', 'quantity_per_listing')
    op.drop_column('catalog_listings', 'sales_unit')
    op.drop_column('catalog_listings', 'short_description')
    # ### end Alembic commands ###
