"""initial schema

Revision ID: 896977388da2
Revises: 
Create Date: 2026-07-27 00:16:36.758670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896977388da2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_location_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='activearchivedstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profiles',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='activearchivedstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_subtypes',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'partially_received', 'received', 'closed', 'cancelled', name='purchaseorderstatus', native_enum=False, length=30), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('is_retroactive', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('subtype_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('shape', sa.String(length=100), nullable=True),
    sa.Column('finish', sa.String(length=100), nullable=True),
    sa.Column('hole_size', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('strand_length', sa.String(length=100), nullable=True),
    sa.Column('count', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('attributes_json', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_status', sa.Enum('none', 'pending', 'available', name='imagestatus', native_enum=False, length=20), nullable=False),
    sa.Column('media_notes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='activearchivedstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['subtype_id'], ['product_subtypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('receipts',
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_listings',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('listing_description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'retired', 'archived', name='cataloglistingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_units',
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('unresolved_description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_type', sa.Enum('strand', 'container', 'bag', 'tube', 'count', 'gram', 'ounce', 'piece', 'pair', 'set', 'unknown', 'other', 'lot', name='unittype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'depleted', 'damaged', 'unresolved', 'archived', name='inventoryunitstatus', native_enum=False, length=20), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=True),
    sa.Column('receipt_line_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['receipt_line_id'], ['receipt_lines.id'], name='fk_inventory_units_receipt_line_id', use_alter=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_lines',
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('expected_item_description', sa.String(length=500), nullable=True),
    sa.Column('expected_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('expected_unit_type', sa.Enum('strand', 'container', 'bag', 'tube', 'count', 'gram', 'ounce', 'piece', 'pair', 'set', 'unknown', 'other', 'lot', name='unittype', native_enum=False, length=20), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('expected', 'partially_received', 'received', 'discrepancy', 'cancelled', name='purchaseorderlinestatus', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_adjustments',
    sa.Column('inventory_unit_id', sa.Uuid(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('manual_correction', 'damaged', 'lost', 'count_correction', 'other', name='inventoryadjustmenttype', native_enum=False, length=30), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('adjusted_by', sa.Uuid(), nullable=True),
    sa.Column('adjusted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adjusted_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_lines',
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('unresolved_item_description', sa.String(length=500), nullable=True),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('received_unit_type', sa.Enum('strand', 'container', 'bag', 'tube', 'count', 'gram', 'ounce', 'piece', 'pair', 'set', 'unknown', 'other', 'lot', name='unittype', native_enum=False, length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('receiving_status', sa.Enum('matched', 'overage', 'shortage', 'substitution', 'damaged', 'unresolved', name='receivingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('discrepancy_notes', sa.String(), nullable=True),
    sa.Column('inventory_unit_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_units.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_lines')
    op.drop_table('inventory_adjustments')
    op.drop_table('purchase_order_lines')
    op.drop_table('inventory_units')
    op.drop_table('catalog_listings')
    op.drop_table('receipts')
    op.drop_table('products')
    op.drop_table('purchase_orders')
    op.drop_table('product_subtypes')
    op.drop_table('vendors')
    op.drop_table('profiles')
    op.drop_table('product_categories')
    op.drop_table('locations')
    # ### end Alembic commands ###
