"""add hints table and product custom_subtype

Revision ID: 984554351b61
Revises: 896977388da2
Create Date: 2026-07-27 15:38:53.973783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984554351b61'
down_revision: Union[str, None] = '896977388da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hints',
    sa.Column('page', sa.String(length=100), nullable=False),
    sa.Column('item_key', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page', 'item_key', name='uq_hints_page_item_key')
    )
    op.add_column('products', sa.Column('custom_subtype', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'custom_subtype')
    op.drop_table('hints')
    # ### end Alembic commands ###
