"""add email_accounts table

Revision ID: d2ddd2085904
Revises: 41947c47e819
Create Date: 2026-08-05 10:32:09.654247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ddd2085904'
down_revision: Union[str, None] = '41947c47e819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('provider', sa.Enum('gmail', 'outlook', name='emailprovider', native_enum=False, length=20), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'needs_reauth', name='emailaccountstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'email_address', name='uq_email_accounts_provider_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
