"""add piece creations and product source type

Revision ID: d6ff40fa4f51
Revises: faed1c8ae678
Create Date: 2026-08-08 12:47:18.062633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ff40fa4f51'
down_revision: Union[str, None] = 'faed1c8ae678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece_creations',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('creation_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_source', sa.Enum('manual', 'estimated_from_components', name='piececostsource', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', name='piececreationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('resulting_inventory_unit_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['resulting_inventory_unit_id'], ['inventory_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piece_components',
    sa.Column('piece_creation_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_unit_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost_at_use', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_units.id'], ),
    sa.ForeignKeyConstraint(['piece_creation_id'], ['piece_creations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'products',
        sa.Column(
            'source_type',
            sa.Enum('purchased', 'assembled', name='productsourcetype', native_enum=False, length=20),
            server_default='purchased',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'source_type')
    op.drop_table('piece_components')
    op.drop_table('piece_creations')
    # ### end Alembic commands ###
