"""add shops table

Revision ID: faed1c8ae678
Revises: d2ddd2085904
Create Date: 2026-08-08 12:38:49.312926

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faed1c8ae678'
down_revision: Union[str, None] = 'd2ddd2085904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


shops_table = sa.table(
    "shops",
    sa.column("id", sa.Uuid()),
    sa.column("name", sa.String()),
    sa.column("created_at", sa.DateTime(timezone=True)),
    sa.column("updated_at", sa.DateTime(timezone=True)),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed the single shop row this deployment represents. Nothing
    # references shops.id yet (see app/models/shop.py) — this just ensures
    # the eventual first FK backfill has exactly one row to point at.
    now = datetime.now(timezone.utc)
    op.bulk_insert(
        shops_table,
        [{"id": uuid.uuid4(), "name": "Patti's Bead Shop", "created_at": now, "updated_at": now}],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shops')
    # ### end Alembic commands ###
